name: mission_control

volumes:
  search-db:

# The braingeneers-net network is used to connect the containers together.
networks:
  braingeneers-net:
    driver: bridge

services:
  search:
    container_name: search
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=search.braingeneers.gi.ucsc.edu
      - VIRTUAL_PORT=8501
      - LETSENCRYPT_HOST=search.braingeneers.gi.ucsc.edu
      - LETSENCRYPT_EMAIL=braingeners-admins-group@ucsc.edu
      - S3_ENDPOINT=https://s3.braingeneers.gi.ucsc.edu
      - S3_PROFILE=prp-braingeneers
      - S3_BUCKET=braingeneers
    volumes:
      # DEV ONLY: Mount local code when developing only
      # - .:/home/app/code:cached
      - ${HOME}/.aws:/root/.aws:cached
      - search-db:/root/data
    ports:
      # DEV ONLY: Forward to local machine for tunnel to browser
      - "127.0.0.1:8080:8080"
    expose:
      - 8501
    command:
      - /bin/bash
      - -c
      - |
        sqlite3 -init create.sql data/braingeneers.db .quit
        cron
        python main.py
    networks:
      - braingeneers-net
