version: '3.8'

name: ${USER}-braingeneers-search

volumes:
  postgres:


services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/home/app/code:cached
      - ${HOME}/.aws:/home/app/.aws:cached
    ports:
      - "127.0.0.1:5000:5000"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # network_mode: service:postgres
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  postgres:
    container_name: postgres
    image: postgres:15.3-bullseye
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
