version: '3.8'

# name: ${USER}-braingeneers-search
name: mission_control

volumes:
  search-db:

    # The braingeneers-net network is used to connect the containers together.
networks:
  braingeneers-net:
    driver: bridge

services:
  search:
    container_name: search
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=search.braingeneers.gi.ucsc.edu
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=search.braingeneers.gi.ucsc.edu
      - LETSENCRYPT_EMAIL=braingeners-admins-group@ucsc.edu
    env_file:
      - postgres.env
    volumes:
      - ${HOME}/.aws:/home/app/.aws:cached
      # DEV ONLY: Mount local code when developig only
      - .:/home/app/code:cached
    ports:
      # DEV ONLY: Forward to local machine for tunnel to browser
      - "127.0.0.1:5000:5000"
    expose:
      - 5000
    command:
      - /bin/bash
      - -c
      - |
        psql $$DATABASE_URL -f code/create.sql
        # flask --app code/server.py run --host 0.0.0.0
        # DEV ONLY: Auto reload when code changes
        flask --app code/server.py --debug run --host 0.0.0.0
    depends_on:
      search-db:
        condition: service_healthy
    networks:
      - braingeneers-net

  search-db:
    container_name: search-db
    image: postgres:15.3-bullseye
    restart: unless-stopped
    volumes:
      - search-db:/var/lib/postgresql/data
    env_file:
      - postgres.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - braingeneers-net
