version: '3.8'

name: ${USER}-braingeneers-search

volumes:
  postgres:


services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=search.braingeneers.gi.ucsc.edu
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=search.braingeneers.gi.ucsc.edu
      - LETSENCRYPT_EMAIL=braingeners-admins-group@ucsc.edu
    env_file:
      - postgres.env
    volumes:
      - .:/home/app/code:cached
      - ${HOME}/.aws:/home/app/.aws:cached
    ports:
      - "127.0.0.1:5000:5000"
    # command: sleep infinity
    command:
      - /bin/bash
      - -c
      - |
        psql $$DATABASE_URL -f code/create.sql
        flask --app code/server.py --debug run --host 0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:15.3-bullseye
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - postgres.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
